### ISSUE TITLE
What does best overlap means?

### ISSUE THREAD

**Issue by Qinying-Liu** [Alvin-Zeng/PGCN#11]
What is best overlap? What is the differences between best iou and best overlap?

**Comment by canbaoburen** [comment]
What is best overlap? What is the differences between best iou and best overlap?

**Comment by P-DX** [comment]
> What is best overlap? What is the differences between best iou and best overlap?

Hi, i have the same question about this
do you have any ideas?

How can we get best overlap without groundtruth when we test.
