### ISSUE TITLE
How to fuse rgb and flow features.

### ISSUE THREAD

**Issue by Fordacre** [Alvin-Zeng/PGCN#12]
Hi, Alvin. Thanks for your excellent work, but I am confused about how you fused the flow and rgb features of I3D model. Is it a simple average function? Cuz most I3D models generate features with 1024 dimensions for both streams, but the fused features in your work are 2048 dimensions.

**Comment by Alvin-Zeng** [comment]
Hi, we have uploaded the trained models and features. We also provide a script for fusing the two-stream features. Please see "test_two_stream.sh"
