### ISSUE TITLE
Question about proposal generation 

### ISSUE THREAD

**Issue by yangwf1** [Alvin-Zeng/PGCN#14]
Hi, thanks for your sharing of the code. I'd like to know that where the pre-extracted proposals come from.  Did you reimplement the paper Boundary Sensitive Network or just use their provided proposals?

**Comment by Alvin-Zeng** [comment]
Hi, we use the proposals provided by the authors of BSN.

**Comment by yangwf1** [comment]
Thanks, I went to the project page of their paper but I cann’t find the link where I can download the extracted proposals.
So I would appreciate it very much if you could provide the download link.

Best wishes!

发送自 Windows 10 版邮件应用

发件人: Runhao Zeng
发送时间: 2020年1月4日 10:13
收件人: Alvin-Zeng/PGCN
抄送: yangwf1; Author
主题: Re: [Alvin-Zeng/PGCN] Question about proposal generation (#14)

Hi, we use the proposals provided by the authors of BSN.

**Comment by Alvin-Zeng** [comment]
Please let me know your email address.

**Comment by yangwf1** [comment]
my email address is yangwf@mail.ustc.edu.cn, thank you

**Comment by Alvin-Zeng** [comment]
Please check your mail box.

**Comment by pranavgundewar** [comment]
Hi, I am facing a similar issue. Can you please email me the proposal as well?
Email: pranavgundewar@gmail.com 
Thanks a ton!

**Comment by tzzcl** [comment]
Hi, I am facing a similar issue. Can you please email me the proposal as well?
Email: zhangcl@lamda.nju.edu.cn
Thanks a ton!

**Comment by semchan** [comment]
me too, would you pls send me the proposal as well? chenyaosen@stu.scu.edu.cn. Thanks very much.

**Comment by shadowclouds** [comment]
> my email address is [yangwf@mail.ustc.edu.cn](mailto:yangwf@mail.ustc.edu.cn), thank you



Hello,coud you provide the proposal list for ActivityNet? my email address: cyz_dai@163.com
