### ISSUE TITLE
About Activitynet feature

### ISSUE THREAD

**Issue by yklilfft** [Alvin-Zeng/PGCN#15]
Hi, thanks  a lot for open resource .I'm working on activitynet dataset. Do u have I3D features u used in this project, I'm appreciate it if u can share one copy to me!
My email address is 727627725@qq.com

**Comment by shadowclouds** [comment]
appreciate for copy of I3D features ,too.
My email address: cyz_dai@163.com

**Comment by shadowclouds** [comment]
Sorry for disturb. Could you provide the bsn_xx.txt for ActivityNet? As for I3D feature, if it's difficult to provide, could you tell us how to generate it?  
My email address: cyz_dai@163.com
Thanks again for your open-source work

**Comment by shadowclouds** [comment]
> Hi, thanks a lot for open resource .I'm working on activitynet dataset. Do u have I3D features u used in this project, I'm appreciate it if u can share one copy to me!
> My email address is [727627725@qq.com](mailto:727627725@qq.com)

hello,have you got the I3D feature or the proposal_list for ActivityNet?  I'm also working on activitynet dataset.

**Comment by Alvin-Zeng** [comment]
@yklilfft @shadowclouds Please check your mailbox.

**Comment by ShaoQiBNU** [comment]
appreciate for copy of I3D features or the proposal_list for ActivityNet?,too.
My email address: ShaoQi_BNU@163.com

**Comment by Qinying-Liu** [comment]
Would you please send my I3D features or the proposal_list for ActivityNet? My email address:1258168813@qq.com @Alvin-Zeng @ShaoQiBNU @shadowclouds
