### ISSUE TITLE
video_validation_0000947 is missing in Flow_Train.tar.gz

### ISSUE THREAD

**Issue by jd730** [Alvin-Zeng/PGCN#16]
Hi, 
I downloaded Flow_Train.tar.gz via google cloud and I found that video_validation_0000947 is missing in Flow_Train.tar.gz while it is existing in Rgb_Train_feature.zip.

Could you reupload the file?

Thank you so much.

**Comment by Alvin-Zeng** [comment]
We found this video contains a ground truth whose duration is close to the whole video. Thus, we neglect it in the training. Please refer to https://raw.githubusercontent.com/yjxiong/action-detection/master/data/thumos14_tag_val_normalized_proposal_list.txt for more details.
