### ISSUE TITLE
Is RGB model saved with float datatype?

### ISSUE THREAD

**Issue by frostinassiky** [Alvin-Zeng/PGCN#17]
Thanks for the brilliant work!

I happen to see an error when the [RGB model](https://github.com/Alvin-Zeng/PGCN/blob/master/results/RGB_cpt.pth) is directly loaded into the PGCN architecture. 
The reason seems to be a mismatch of the datatype.

To solve that, I replaced one line of code in [pgcn_test.py](https://github.com/Alvin-Zeng/PGCN/blob/46428daf719f7d655f19b3f27ed879bd88d91158/pgcn_test.py#L161)
```reg_scores[prop_idx, :] = net((act_batch_var, comp_batch_var), None, None, None)```
by
```reg_scores[prop_idx, :] = net((act_batch_var.float(), comp_batch_var.float()), None, None, None)```

Do it first if you find a similar error :)

**Comment by shadowclouds** [comment]
There is also error for RGB model at the training part

**Comment by shadowclouds** [comment]
> Thanks for the brilliant work!
> 
> I happen to see an error when the [RGB model](https://github.com/Alvin-Zeng/PGCN/blob/master/results/RGB_cpt.pth) is directly loaded into the PGCN architecture.
> The reason seems to be a mismatch of the datatype.
> 
> To solve that, I replaced one line of code in [pgcn_test.py](https://github.com/Alvin-Zeng/PGCN/blob/46428daf719f7d655f19b3f27ed879bd88d91158/pgcn_test.py#L161)
> `reg_scores[prop_idx, :] = net((act_batch_var, comp_batch_var), None, None, None)`
> by
> `reg_scores[prop_idx, :] = net((act_batch_var.float(), comp_batch_var.float()), None, None, None)`
> 
> Do it first if you find a similar error :)

Does the result of RGB model normal? I change the RGB model to float but the results are quite low.However, the RGB_result author provided is norm.

**Comment by frostinassiky** [comment]
@shadowclouds Mine looks good. The RGB model is slightly worse than the optical flow model. Combining both of them can still get me a boosted performance.

**Comment by Alvin-Zeng** [comment]
Before forwarding the RGB features to the model, you should change them to a float datatype by using .float()
