### ISSUE TITLE
custom videos

### ISSUE THREAD

**Issue by xianguo-dev** [Alvin-Zeng/PGCN#18]
Thanks for your code,but is it able to train and test custom videos?

**Comment by Alvin-Zeng** [comment]
Of course! You could generate the proposals of your videos and use our PGCN to process these proposals.

**Comment by xianguo-dev** [comment]
Hi!I wonder how could I know the specific time of the action in videos?Cause I can merely get the map to evaluate while I would like to get the lenghth of the action.But I have no idea of doing this job.Could you please give me some advice?Thanks a lot!
