### ISSUE TITLE
 the proposal_list for ActivityNet

### ISSUE THREAD

**Issue by ShaoQiBNU** [Alvin-Zeng/PGCN#19]
hello,have you got the I3D feature or the proposal_list for ActivityNet? I'm also working on activitynet dataset. Thank you!
My email is  ShaoQi_BNU@163.com

**Comment by shadowclouds** [comment]
hello,I also want the proposal_list  for ActivityNet? And the link of Flow feature you provide for ActivityNet is out-of-date, could you update it?
My email address again: cyz_dai@163.com

**Comment by shadowclouds** [comment]
> hello,have you got the I3D feature or the proposal_list for ActivityNet? I'm also working on activitynet dataset. Thank you!
> My email is [ShaoQi_BNU@163.com](mailto:ShaoQi_BNU@163.com)

Hello, I'm also work on ActivityNet, could we dicuss about it? 
my weixin:cyzdai

**Comment by Alvin-Zeng** [comment]
I have sent the proposal list to your mailbox. Feel free to contact me if you have any questions.

**Comment by xianguo-dev** [comment]
@Alvin-Zeng Hi!I am struggling to generate my own datasets's "proposal list" just like [https://github.com/yjxiong/action-detection/blob/master/data/thumos14_tag_test_normalized_proposal_list.txt](url).Do you have code to generate it?

I'll be much thankful if you could offer me some information.

**Comment by Alvin-Zeng** [comment]
Please refer to https://github.com/yjxiong/action-detection/wiki/A-Description-of-the-Proposal-Files for the description of the proposal files. A simple script could generate the proposal list.

**Comment by xianguo-dev** [comment]
Yeah！Thank you so much for your reply.However I have read this description and still confused about generating my own proposal list.

It would be much generous if you could send me the script anytime available .

Sorry to interrupt and I would close this issue if you are willing to response for me.Thanks again!

**Comment by PeisenZhao** [comment]
Hello,I also want the proposal_list for ActivityNet? 
My email address: pszhao@sjtu.edu.cn

**Comment by Mengwen-Xu** [comment]
@xianguo-dev
I am struggling to generate my own datasets's "proposal list"，Do you have code to generate it?

**Comment by Alvin-Zeng** [comment]
We have uploaded the Anet proposals, please find them in README.md
