### ISSUE TITLE
An error when pickle load the .pkl in data/

### ISSUE THREAD

**Issue by dingli-dean** [Alvin-Zeng/PGCN#2]
Hello, an error occured when load the ./data/thumos14_train_prop_dict.pkl

`UnpicklingError                           Traceback (most recent call last)
----> 1 data = pickle.load(open('/home/ld/tac/PGCN/data/thumos14_train_prop_dict.pkl', 'rb'))
UnpicklingError: pickle data was truncated
`
Could you checked the .pkl file?

**Comment by Alvin-Zeng** [comment]
Hi, it seems that you terminated the program when generating the pickle file. Please delete the existing pickle file and re-run the codes.

**Comment by Willforcv** [comment]
> Hi, it seems that you terminated the program when generating the pickle file. Please delete the existing pickle file and re-run the codes.

how to get  thumos14 proposal pkl
