### ISSUE TITLE
Could you please explain the meaning of some parameters

### ISSUE THREAD

**Issue by Tylerjoe** [Alvin-Zeng/PGCN#23]
Thanks for your great work, but I have some parameters which I don't understand
https://github.com/Alvin-Zeng/PGCN/blob/46428daf719f7d655f19b3f27ed879bd88d91158/pgcn_models.py#L157

could you please explain the meaning of parameters: self.adj_num, self.child_num ?
And I don't find how to select the contextual edges and surrounding edges as said in your paper. 
I‘m confused how to find the edges or mask in this part, could you please give me a kind help? Thanks

**Comment by Alvin-Zeng** [comment]
#child_num is the number of neighborhoods for each node
#adj_num: please refer to #4 
how to construct the graph: please refer to #4
