### ISSUE TITLE
training error, please help

### ISSUE THREAD

**Issue by semchan** [Alvin-Zeng/PGCN#24]
fg, incomp, bg = self.prop_dict[video.id][0], self.prop_dict[video.id][1], self.prop_dict[video.id][2]
KeyError: 'video_validation_0000187'

**Comment by Alvin-Zeng** [comment]
Could you please provide more details about the error?

**Comment by semchan** [comment]
> Could you please provide more details about the error?

already fixed. it is caused by the datafile is not generated completely when training. thanks.

**Comment by mrlihellohorld** [comment]
> > Could you please provide more details about the error?
> 
> already fixed. it is caused by the datafile is not generated completely when training. thanks.

Hello, I have the same problem, can you tell me how to solve it?
