### ISSUE TITLE
Using G-TAD results In PGCN :

### ISSUE THREAD

**Issue by lakshaymehra** [Alvin-Zeng/PGCN#28]
Hi,

I am trying to use PGCN on my own dataset. I have annotated the data according to Thumos'14 annotation format and extracted features using I3D. I have also trained and infered a G-TAD model.

1. Can you let me know how I can re-score G-TAD generated output using PGCN?

Your answers to the above questions will clarify a lot of doubts.

Thank you for your time!

**Comment by lakshaymehra** [comment]
??

**Comment by Alvin-Zeng** [comment]
If you use G-TAD to generate proposals, you could generate a proposal list for training PGCN. Please refer to https://github.com/yjxiong/action-detection/wiki/A-Description-of-the-Proposal-Files for more details about the format of the proposal list.

**Comment by mugenggeng** [comment]
> 你好
> 
> 我正在尝试在我自己的数据集上使用PGCN。我根据 Thumos'14 注释格式对数据进行了注释，并使用 I3D 提取了特征。我还训练并推断了一个G-TAD模型。
> 
> 1. 你能告诉我如何使用PGCN重新评分G-TAD生成的输出吗？
> 
> 您对上述问题的回答将澄清很多疑问。
> 
> 谢谢你的时间！

Excuse me, have you solved it？
