### ISSUE TITLE
How to exact feature from video？And how to generate proposal txt?

### ISSUE THREAD

**Issue by Healingl** [Alvin-Zeng/PGCN#29]
How to exact I3D feature from origin video？Could you share data preprocess code or feature exaction code？And how to generate proposal txt from custom video? Thx~

**Comment by Alvin-Zeng** [comment]
1. We follow the same format as that is used in SSN to generate the proposal list. Please refer to https://github.com/yjxiong/action-detection.
2. Codes for extracting I3D features: https://github.com/hassony2/kinetics_i3d_pytorch
