### ISSUE TITLE
请问有没有activitynet1.3上的特征提供下载

### ISSUE THREAD

**Issue by Zhuysheng** [Alvin-Zeng/PGCN#3]

**Comment by Alvin-Zeng** [comment]
Hi, we are now working on the codes for feature extraction and pre-processing. And we will make them publicly available.

**Comment by Lechatelia** [comment]
Hello！ @Alvin-Zeng 
I tried to write some pre-processing and feature extraction codes myself, but the features extracted are still very different from yours. Can you open source this part of the codes or send it to my email, which I want to compare with my work. It doesn't matter if it is not organized well.
My email is lechatelia@stu.xjtu.edu.cn
