### ISSUE TITLE
question about the I3D feature

### ISSUE THREAD

**Issue by JJBOY** [Alvin-Zeng/PGCN#33]
In your paper, it says "We first uniformly divide each input video into 64-frame segments. We then use a two-stream Inflated 3D ConvNet (I3D) model pre-trained on Kinetics [5] to extract the segment features." 
However, in your code

```
interval = 8
clip_length = 64
start_unit = int(min(ft_num - 1, np.floor(float(start_ind + off) / interval)))
end_unit = int(min(ft_num - 2, np.ceil(float(end_ind - clip_length) / interval)))
```

I guess minusing 64 means you do not use the last few frames not divisible by 64, but why should interval=8? 
Is it means that you divide each input video into 8-frame?

By the way?  Could you offer the  I3D feature on ActivityNet?  It's so time-comsuming to extrat.

**Comment by Alvin-Zeng** [comment]
1.  "do not use the last few frames not divisible by 64" --- correct
2. We extract features in using sliding windows and the stride is set to 8.
3. We have uploaded the I3D Anet features, please find them in README.md

**Comment by JJBOY** [comment]
Thanks very much for your reply and your feature！
