### ISSUE TITLE
About incomplete_overlap_thresh

### ISSUE THREAD

**Issue by blowing-wind** [Alvin-Zeng/PGCN#34]
Hi, the incomplete_overlap_thresh in current_configs.yaml is set to be 0.01, however, I think it should be around 0.7?

**Comment by Alvin-Zeng** [comment]
We follow SSN https://github.com/yjxiong/action-detection/blob/master/data/dataset_cfg.yaml and set this threshold to 0.01 to include more incomplete samples on THUMOS14.
