### ISSUE TITLE
我想问一下bsn_train_proposal_list.txt中的pre_box是怎么得到的？

### ISSUE THREAD

**Issue by wenzhendeng** [Alvin-Zeng/PGCN#36]
您好，我想问一下bsn_train_proposal_list.txt中的pre_box是怎么得到的，特别是box对应的label？如果我想用自己的数据训练，怎么得到数据对应的label以及pre_box

**Comment by Alvin-Zeng** [comment]
你好，你把box与这个视频中所有的GT计算一下IoU，看最大IoU对应的GT，即可知道这个box对应哪个GT

**Comment by wenzhendeng** [comment]
您好，非常感谢，在label, best_iou, overlap_self, start_frame, end_frame这几个参数重，我的理解是与哪个gt的iou最大，则对应这个gt的label以及这个best_iou就是这个最大的iou，但是overlap_self是怎么得到的呢？

**Comment by wenzhendeng** [comment]
> 你好，你把box与这个视频中所有的GT计算一下IoU，看最大IoU对应的GT，即可知道这个box对应哪个GT
您好，非常感谢，在label, best_iou, overlap_self, start_frame, end_frame这几个参数重，我的理解是与哪个gt的iou最大，则对应这个gt的label以及这个best_iou就是这个最大的iou，但是overlap_self是怎么得到的呢？

**Comment by wenzhendeng** [comment]
> 你好，你把box与这个视频中所有的GT计算一下IoU，看最大IoU对应的GT，即可知道这个box对应哪个GT

您好，非常感谢，在label, best_iou, overlap_self, start_frame, end_frame这几个参数重，我的理解是与哪个gt的iou最大，则对应这个gt的label以及这个best_iou就是这个最大的iou，但是overlap_self是怎么得到的呢？

**Comment by Alvin-Zeng** [comment]
MAX_OVERLAP stands for the maximal overlap with groundtruth proportional to the length of this proposal.
可参考：https://github.com/yjxiong/action-detection/wiki/A-Description-of-the-Proposal-Files

**Comment by wenzhendeng** [comment]
> MAX_OVERLAP stands for the maximal overlap with groundtruth proportional to the length of this proposal.
> 可参考：https://github.com/yjxiong/action-detection/wiki/A-Description-of-the-Proposal-Files
非常感谢，但是这样是不是就有一个问题，对没有标注文件的视频，比如从网上下载的视频，岂不是就没办法得到其对应的proposal了吗，因为在处理新的数据时，好像必须要best_iou和overlap_self

**Comment by Alvin-Zeng** [comment]
是的，所以需要你事先生成proposal，再用PGCN的方法对proposal进行处理

**Comment by DRJ2016** [comment]
您好，如果我没有理解错的话，您的意思是，如果要对一个视频进行动作定位，首先这个视频要有动作定位的标签来生成proposal，没有标签的话无法得到best_iou和overlap_self？您的意思是要用答案来求解答案吗？
