### ISSUE TITLE
A detail question about the model

### ISSUE THREAD

**Issue by HaiyiMei** [Alvin-Zeng/PGCN#4]
Hey! Great Job!
After seeing through your paper, I've got one question. I was wondering how did you process the output feature of GCN model (Nxd) before fc layer. Because you know, you got to get rid of the two dimensions.
And I saw the [code](https://github.com/Alvin-Zeng/PGCN/blob/7b604816308d41f00dd3bdfcf3260e05764cb8af/pgcn_models.py#L179), found that you just picked the first row of all N features. Did I understand it correctly? If so, could you please explain why would you do that. Why not perform an average pool between the N features? Thanks a lot!

**Comment by Alvin-Zeng** [comment]
Thanks!
We indeed select the first row out of the N rows as the proposal feature to train our model. In the current version of P-GCN, for each proposal p, we first select the proposals that will affect p through multiple graph convolution layers. Then, we construct a proposal tree for this proposal relying on the contextual and surrounding rules. When the number of the neighbourhood is set to 10 and the number of GCN layer is set to 2, this tree will contain 1+10+10x10=111 nodes.

Please note that this proposal tree is equivalent to the proposal graph when we only take the node on top to train our PGCN model. We are now working on a graph-based version, and we will release it soon.

**Comment by ray342649093** [comment]
if you take a look at the pgcn_dataset file, you will then find that the first row of the features is the center prop features.(from the _video_centric_sampling, the _sample_adjacent_proposals, and the _sample_proposals_via_graph methods)

**Comment by HaiyiMei** [comment]
Thank you guys for the quick reply.
