### ISSUE TITLE
How to run this model on a New datasets

### ISSUE THREAD

**Issue by makecent** [Alvin-Zeng/PGCN#41]
I would like to test your model on a new TAL dataset collected by our laboratory. Hence we want to know how should we prepare the dataset directory and ground truth files. Any suggestions will be very helpful!

**Comment by rahulrajus** [comment]
Hey! Have you made any progress on training on new datasets?

**Comment by makecent** [comment]
> Hey! Have you made any progress on training on new datasets?

I made it. I use the [mmaction2](https://github.com/open-mmlab/mmaction2) repository to generate the proposals for the new dataset and use them to train the PGCN successfully. PGCN works pretty well.

**Comment by menghuaa** [comment]
> > Hey! Have you made any progress on training on new datasets?
> 
> I made it. I use the [mmaction2](https://github.com/open-mmlab/mmaction2) repository to generate the proposals for the new dataset and use them to train the PGCN successfully. PGCN works pretty well.



> > Hey! Have you made any progress on training on new datasets?
> 
> I made it. I use the [mmaction2](https://github.com/open-mmlab/mmaction2) repository to generate the proposals for the new dataset and use them to train the PGCN successfully. PGCN works pretty well.

Hey! How you generate the proposals?

**Comment by makecent** [comment]
> > > Hey! Have you made any progress on training on new datasets?
> > 
> > 
> > I made it. I use the [mmaction2](https://github.com/open-mmlab/mmaction2) repository to generate the proposals for the new dataset and use them to train the PGCN successfully. PGCN works pretty well.
> 
> > > Hey! Have you made any progress on training on new datasets?
> > 
> > 
> > I made it. I use the [mmaction2](https://github.com/open-mmlab/mmaction2) repository to generate the proposals for the new dataset and use them to train the PGCN successfully. PGCN works pretty well.
> 
> Hey! How you generate the proposals?

I used the BMN, which is supported in the mmaction2 repository.

**Comment by menghuaa** [comment]
> > > > Hey! Have you made any progress on training on new datasets?
> > > 
> > > 
> > > I made it. I use the [mmaction2](https://github.com/open-mmlab/mmaction2) repository to generate the proposals for the new dataset and use them to train the PGCN successfully. PGCN works pretty well.
> > 
> > 
> > > > Hey! Have you made any progress on training on new datasets?
> > > 
> > > 
> > > I made it. I use the [mmaction2](https://github.com/open-mmlab/mmaction2) repository to generate the proposals for the new dataset and use them to train the PGCN successfully. PGCN works pretty well.
> > 
> > 
> > Hey! How you generate the proposals?
> 
> I used the BMN, which is supported in the mmaction2 repository.

Hi!How you generate the features of proposals?

**Comment by makecent** [comment]
> > > > > Hey! Have you made any progress on training on new datasets?
> > > > 
> > > > 
> > > > I made it. I use the [mmaction2](https://github.com/open-mmlab/mmaction2) repository to generate the proposals for the new dataset and use them to train the PGCN successfully. PGCN works pretty well.
> > > 
> > > 
> > > > > Hey! Have you made any progress on training on new datasets?
> > > > 
> > > > 
> > > > I made it. I use the [mmaction2](https://github.com/open-mmlab/mmaction2) repository to generate the proposals for the new dataset and use them to train the PGCN successfully. PGCN works pretty well.
> > > 
> > > 
> > > Hey! How you generate the proposals?
> > 
> > 
> > I used the BMN, which is supported in the mmaction2 repository.
> 
> Hi!How you generate the features of proposals?

Just following the PGCN: using a I3D pre-trained on Kinetics to extract features on the new dataset. You may refer to step 6 [here](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/activitynet).

**Comment by try-harder12** [comment]
Hello, I would like to ask how you processed the proposal result generated by BMN to convert it into the proposal format required by PGCN？ @makecent 
Looking forward to your help！

**Comment by henryrobbins** [comment]
@try-harder12 did you have any success with this? I'm about to attempt the same thing myself. In the [BSN README](https://github.com/open-mmlab/mmaction2/blob/main/configs/localization/bsn/README.md), it mentions a script `tools/data/activitynet/convert_proposal_format.py` which can convert into the proposal format for SSN or P-GCN.
