### ISSUE TITLE
Which flow algorithm did you use for this project?

### ISSUE THREAD

**Issue by ray342649093** [Alvin-Zeng/PGCN#5]
Hi, I was wondering what flow algorithm did you use to generate the flow map for extracting I3D flow features?

**Comment by Alvin-Zeng** [comment]
Hi, we follow TSN and use the dense flow tools to obtain the optical flow. See the link below:
[https://github.com/wanglimin/dense_flow](url)

**Comment by ghost** [comment]
> Hi, we follow TSN and use the dense flow tools to obtain the optical flow. See the link below:
> [https://github.com/wanglimin/dense_flow](url)
Hi,how do you extract the I3D Flow Feature which you provide on the Baidu Yun ?

**Comment by ghost** [comment]
what the feature type? I can not use vscode or potplayer to open the feature， how can i open it ?

**Comment by Alvin-Zeng** [comment]
Hi, we use the codes in https://github.com/hassony2/kinetics_i3d_pytorch to extract features. The features are stored by using "torch.save()".
