### ISSUE TITLE
how to generate bsn_proposal_list.txt

### ISSUE THREAD

**Issue by ppannattee** [Alvin-Zeng/PGCN#6]
thank you for your great work.
I have some question wether if I want to apply your work for my own dataset how can i generate the bsn_proposal_list files ? and am I need to train bsn proposal generator with my own dataset ?

thank you so much

**Comment by Alvin-Zeng** [comment]
Hi, I am sorry for the late reply.
1. We follow the same format as that is used in SSN to generate the proposal list. Please refer to https://github.com/yjxiong/action-detection.
2. You need to train the bsn proposal generator on your own dataset.

**Comment by Fordacre** [comment]
Hi, can I get the bsn_proposal_list.txt for anet @Alvin-Zeng ? Thanks.

**Comment by Alvin-Zeng** [comment]
Sure, let me know your email address.

**Comment by ShaoQiBNU** [comment]
Hi, I also want to get the bsn_proposal_list.txt for anet @Alvin-Zeng ? Thanks.
My email address is ShaoQi_BNU@163.com

**Comment by ShaoQiBNU** [comment]
另外，我想请教一个问题， bsn_proposal_list.txt的生成是先在bsn模型上训练，然后生成proposal，之后再https://github.com/yjxiong/action-detection按照这里的方法生成list吗？BSN的输出是["xmin","xmax","xmin_score","xmax_score","score","match_iou","match_ioa"]，请问这个与你的数据是如何对应的？谢谢~~~

**Comment by ShaoQiBNU** [comment]
> Hi, can I get the bsn_proposal_list.txt for anet @Alvin-Zeng ? Thanks.

Hi, I also want to get the bsn_proposal_list.txt for anet @Alvin-Zeng ? Thanks.
My email address is ShaoQi_BNU@163.com

**Comment by hollowgalaxy** [comment]
Why do you link ssn proposal generation when in the paper you mention that you use BSN proposals? Are they the same model? Am I missing something here? @Alvin-Zeng
