### ISSUE TITLE
Pre-trained model on THUMOS'14 for testing purpose

### ISSUE THREAD

**Issue by pranavgundewar** [Alvin-Zeng/PGCN#7]
Hi, thanks for your work!

Can you please share your pre-trained model on THUMOS'14 dataset? Thank you.

**Comment by Alvin-Zeng** [comment]
Sure, let me know your email address.

**Comment by pranavgundewar** [comment]
Hi!

Can you please email the pre-trained model to pranavgundewar@gmail.com?

Thank you so much for sharing the code base and continue the great work.
Regards,
Pranav Gundewar

**Comment by Alvin-Zeng** [comment]
Hi, we have uploaded the trained models and RGB features.
